### ISSUE TITLE
Filling two long values appears to cause the second to be filled the same way as the first

### ISSUE THREAD

**Issue by meggle** [MisterJames/GenFu#64]
For example, if I have two longs like long Id and long BatchId, and Id is something like incrementingId++ and BatchId is .WithRandom(new List<long> { 1, 2, 3, 4, 5 }), BatchId will always be the Id++ and not one of the random values. 

However, if i switch Id to an int, suddenly BatchId is within the random range I have defined.

I have some sample code with xunit: 

```
 using Xunit;
 using GenFu;
 using System.Collections.Generic;
 using System;

 namespace MyFirstDnxUnitTests
  {
    public class GenFuTest
    {
    [Fact]
    public void CreateFakeTestData()
    {
        CreateFakeData();
    }

    public void CreateFakeData()
    {
        var ab = new string[]
    {
            "A",
            "B"
    };
        var id = 0;
        GenFu.GenFu.Configure<TestDataType>()
        //this is id++
            .Fill(p => p.Id, () => id++)
       //this is now id++ +1
            .Fill(p => p.BatchId).WithRandom(new List<long> { 1, 2, 3, 4, 5 })
            .Fill(p => p.User).AsFirstName()
            .Fill(p => p.Type).WithinRange(1, 5)
            .Fill(p => p.IsActive).WithRandom(new bool[] { true, false })
            .Fill(p => p.Amount).WithinRange(1, 1000)
            .Fill(p => p.CompleteDate, () => DateTime.MinValue)
            .Fill(p => p.AOrB).WithRandom(ab);

        var testData = A.ListOf<TestDataType>(100);
    }

}

public class TestDataType2
{
    public long Id { get; set; }
    public long BatchId { get; set; }
    public string User { get; set; }
    public string AOrB { get; set; }
    public bool IsActive { get; set; }
    public decimal Amount { get; set; }

    public int Type { get; set; }
    public DateTime CompleteDate { get; set; }
}
}
```

**Comment by MisterJames** [comment]
Great report, thanks @meggle, I'll try to repro with that test. Did you want to take this on as a PR?

**Comment by meggle** [comment]
I'll give it a shot

**Comment by engineerclark** [comment]
I experienced this same issue today, except with `int`s rather than `long`s.  It looks to me like the issue has less to do with type, and more to do with the [GetMatchingPropertyFiller](https://github.com/MisterJames/GenFu/blob/b2b7eafc4ed0566ef4279b77ef7c539388fdf50e/src/GenFu/FillerManager.cs#L217-L230) method in FillerManager.cs, which isn't looking up exact matches:

```c#
if (propertyFiller.PropertyType == propertyInfo.PropertyType &&
    propertyFiller.PropertyNames.Any(s => propertyInfo.Name.ToLowerInvariant().Contains(s.ToLowerInvariant())))
{
    result = propertyFiller;
    break;
}
```

Since the conditional is using a `.Contains()`, and the property name `Id` is a substring of `BatchId`, this method will inadvertently return the property filler for `Id` instead.

My temporary workaround was to swap the order in which I add the fillers, causing the more ambiguous property name to be the second one compared, rather than the first.  Applied to your example above:

```c#
        GenFu.GenFu.Configure<TestDataType>()
            .Fill(p => p.BatchId).WithRandom(new List<long> { 1, 2, 3, 4, 5 })
            .Fill(p => p.Id, () => id++)
            // ...
```

**Comment by stimms** [comment]
Looks like this is solved already.
