### ISSUE TITLE
Guid generation not working

### ISSUE THREAD

**Issue by ihandley** [MisterJames/GenFu#75]
I'm sure I'm missing something obvious, but when I try a very simple test to generate a Guid like this:

`var foo = A.New<Guid>();`

What I get is this:

`00000000-0000-0000-0000-000000000000`

I thought maybe it was the most recent version so I rolled back to the last, but alas, same issue.

**Comment by MisterJames** [comment]
Thanks, looks like you found a bug with the way that we generate a `Guid`, which is a special entity because you can new up an object and it will have a valid value (albeit, all zeros).

This also led me to discover a defect with the default value checker, which was not testing properties of type `Guid` for the default value.
